//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//
//     Date:    1/13/2010
//     Time:    10:18 PM
//     Version: 5.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace HongPhat.DataAccess
{
	#region AGENTS_Update Wrapper
    /// <summary>
    /// This class is a wrapper for the AGENTS_Update stored procedure.
    /// </summary>
    public class AGENTS_Update
    {
		#region Member Variables
		protected string _connectionString = String.Empty;
		protected int _recordsAffected = -1;
		protected int _returnValue = 0;
		protected SqlInt32 _agentId = SqlInt32.Null;
		protected bool _agentIdSet = false;
		protected SqlString _agentName = SqlString.Null;
		protected bool _agentNameSet = false;
		protected SqlString _createdBy = SqlString.Null;
		protected bool _createdBySet = false;
		protected SqlDateTime _createdDate = SqlDateTime.Null;
		protected bool _createdDateSet = false;
		protected SqlString _modifiedBy = SqlString.Null;
		protected bool _modifiedBySet = false;
		protected SqlDateTime _modifiedDate = SqlDateTime.Null;
		protected bool _modifiedDateSet = false;
		protected SqlInt32 _idAgentKind = SqlInt32.Null;
		protected bool _idAgentKindSet = false;
		protected SqlInt32 _deleted = SqlInt32.Null;
		protected bool _deletedSet = false;
		#endregion
		
		#region Constructors
		public AGENTS_Update()
		{
		}
		
		public AGENTS_Update(string connectionString)
		{
			this.ConnectionString = connectionString;
		}
		#endregion
		
		#region Public Properties
		/// <summary>
		/// The connection string to use when executing the AGENTS_Update stored procedure.
		/// </summary>
		public string ConnectionString
		{
			get {return _connectionString;}
			set {_connectionString = value;}
		}
		
		/// <summary>
		/// Gets the return value from the AGENTS_Update stored procedure.
		/// </summary>
		public int ReturnValue
		{
			get {return _returnValue;}
		}
		
		/// <summary>
		/// Gets the number of rows changed, inserted, or deleted by execution of the AGENTS_Update stored procedure.
		/// </summary>
		public int RecordsAffected
		{
			get {return _recordsAffected;}
		}
		
		/// <summary>
		/// 
		/// </summary>
		public SqlInt32 AgentId
		{
			get {return _agentId;}
			set
			{
				_agentId = value;
				_agentIdSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlString AgentName
		{
			get {return _agentName;}
			set
			{
				_agentName = value;
				_agentNameSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlString CreatedBy
		{
			get {return _createdBy;}
			set
			{
				_createdBy = value;
				_createdBySet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlDateTime CreatedDate
		{
			get {return _createdDate;}
			set
			{
				_createdDate = value;
				_createdDateSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlString ModifiedBy
		{
			get {return _modifiedBy;}
			set
			{
				_modifiedBy = value;
				_modifiedBySet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlDateTime ModifiedDate
		{
			get {return _modifiedDate;}
			set
			{
				_modifiedDate = value;
				_modifiedDateSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlInt32 IdAgentKind
		{
			get {return _idAgentKind;}
			set
			{
				_idAgentKind = value;
				_idAgentKindSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlInt32 Deleted
		{
			get {return _deleted;}
			set
			{
				_deleted = value;
				_deletedSet = true;
			}
		}
		#endregion
		
		#region Execute Methods
		/// <summary>
		/// This method calls the AGENTS_Update stored procedure.
		/// </summary>
		public virtual void Execute()
		{
			SqlCommand cmd = new SqlCommand();
			
			System.Diagnostics.Debug.Assert(this.ConnectionString.Length != 0, "You must first set the ConnectionString property before calling this method.");
			SqlConnection cn = new SqlConnection(this.ConnectionString);
			
			try
			{
				cmd.Connection = cn;
				cmd.CommandText = "[dbo].[AGENTS_Update]";
				cmd.CommandType = CommandType.StoredProcedure;
				
				#region Populate Parameters
				SqlParameter prmReturnValue = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int);
				prmReturnValue.Direction = ParameterDirection.ReturnValue;
				
				SqlParameter prmAgentId = cmd.Parameters.Add("@AgentId", SqlDbType.Int);
				prmAgentId.Direction = ParameterDirection.Input;
				if (_agentIdSet == true || this.AgentId.IsNull == false)
				{
					prmAgentId.Value = this.AgentId;
				}
				
				SqlParameter prmAgentName = cmd.Parameters.Add("@AgentName", SqlDbType.NVarChar);
				prmAgentName.Direction = ParameterDirection.Input;
					prmAgentName.Size = 250;
				if (_agentNameSet == true || this.AgentName.IsNull == false)
				{
					prmAgentName.Value = this.AgentName;
				}
				
				SqlParameter prmCreatedBy = cmd.Parameters.Add("@CreatedBy", SqlDbType.NVarChar);
				prmCreatedBy.Direction = ParameterDirection.Input;
					prmCreatedBy.Size = 250;
				if (_createdBySet == true || this.CreatedBy.IsNull == false)
				{
					prmCreatedBy.Value = this.CreatedBy;
				}
				
				SqlParameter prmCreatedDate = cmd.Parameters.Add("@CreatedDate", SqlDbType.DateTime);
				prmCreatedDate.Direction = ParameterDirection.Input;
				if (_createdDateSet == true || this.CreatedDate.IsNull == false)
				{
					prmCreatedDate.Value = this.CreatedDate;
				}
				
				SqlParameter prmModifiedBy = cmd.Parameters.Add("@ModifiedBy", SqlDbType.NVarChar);
				prmModifiedBy.Direction = ParameterDirection.Input;
					prmModifiedBy.Size = 250;
				if (_modifiedBySet == true || this.ModifiedBy.IsNull == false)
				{
					prmModifiedBy.Value = this.ModifiedBy;
				}
				
				SqlParameter prmModifiedDate = cmd.Parameters.Add("@ModifiedDate", SqlDbType.DateTime);
				prmModifiedDate.Direction = ParameterDirection.Input;
				if (_modifiedDateSet == true || this.ModifiedDate.IsNull == false)
				{
					prmModifiedDate.Value = this.ModifiedDate;
				}
				
				SqlParameter prmIdAgentKind = cmd.Parameters.Add("@IdAgentKind", SqlDbType.Int);
				prmIdAgentKind.Direction = ParameterDirection.Input;
				if (_idAgentKindSet == true || this.IdAgentKind.IsNull == false)
				{
					prmIdAgentKind.Value = this.IdAgentKind;
				}
				
				SqlParameter prmDeleted = cmd.Parameters.Add("@Deleted", SqlDbType.Int);
				prmDeleted.Direction = ParameterDirection.Input;
				if (_deletedSet == true || this.Deleted.IsNull == false)
				{
					prmDeleted.Value = this.Deleted;
				}
				#endregion
				
				#region Execute Command
				cn.Open();
				_recordsAffected = cmd.ExecuteNonQuery();
				#endregion
				
				#region Get Output Parameters
				if (prmReturnValue.Value != null && prmReturnValue.Value != DBNull.Value)
				{
					_returnValue = (int)prmReturnValue.Value;
				}
				
				#endregion
			}
			finally
			{
				if (cn.State == ConnectionState.Open)
				{
					cn.Close();
				}
				
				cn.Dispose();
				cmd.Dispose();
			}
		}
		
		/// <summary>
		/// This method calls the AGENTS_Update stored procedure.
		/// </summary>
		/// <param name="connectionString">The connection string to use</param>
		/// <param name="agentId"></param>
		/// <param name="agentName"></param>
		/// <param name="createdBy"></param>
		/// <param name="createdDate"></param>
		/// <param name="modifiedBy"></param>
		/// <param name="modifiedDate"></param>
		/// <param name="idAgentKind"></param>
		/// <param name="deleted"></param>
		public static void Execute(
				#region Parameters
				string connectionString,
				SqlInt32 agentId,
				SqlString agentName,
				SqlString createdBy,
				SqlDateTime createdDate,
				SqlString modifiedBy,
				SqlDateTime modifiedDate,
				SqlInt32 idAgentKind,
				SqlInt32 deleted
				#endregion
		    )
		{
			AGENTS_Update aGENTS_Update = new AGENTS_Update();
			
			#region Assign Property Values
			aGENTS_Update.ConnectionString = connectionString;
			aGENTS_Update.AgentId = agentId;
			aGENTS_Update.AgentName = agentName;
			aGENTS_Update.CreatedBy = createdBy;
			aGENTS_Update.CreatedDate = createdDate;
			aGENTS_Update.ModifiedBy = modifiedBy;
			aGENTS_Update.ModifiedDate = modifiedDate;
			aGENTS_Update.IdAgentKind = idAgentKind;
			aGENTS_Update.Deleted = deleted;
			#endregion
			
			aGENTS_Update.Execute();
			
			#region Get Property Values
			
			#endregion
		}
		#endregion
	}
	#endregion
}
