//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//
//     Date:    1/13/2010
//     Time:    10:19 PM
//     Version: 5.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace HongPhat.DataAccess
{
	#region RETURNED_ITEM_DETAILS_Delete Wrapper
    /// <summary>
    /// This class is a wrapper for the RETURNED_ITEM_DETAILS_Delete stored procedure.
    /// </summary>
    public class RETURNED_ITEM_DETAILS_Delete
    {
		#region Member Variables
		protected string _connectionString = String.Empty;
		protected int _recordsAffected = -1;
		protected int _returnValue = 0;
		protected SqlInt32 _orderDetailId = SqlInt32.Null;
		protected bool _orderDetailIdSet = false;
		#endregion
		
		#region Constructors
		public RETURNED_ITEM_DETAILS_Delete()
		{
		}
		
		public RETURNED_ITEM_DETAILS_Delete(string connectionString)
		{
			this.ConnectionString = connectionString;
		}
		#endregion
		
		#region Public Properties
		/// <summary>
		/// The connection string to use when executing the RETURNED_ITEM_DETAILS_Delete stored procedure.
		/// </summary>
		public string ConnectionString
		{
			get {return _connectionString;}
			set {_connectionString = value;}
		}
		
		/// <summary>
		/// Gets the return value from the RETURNED_ITEM_DETAILS_Delete stored procedure.
		/// </summary>
		public int ReturnValue
		{
			get {return _returnValue;}
		}
		
		/// <summary>
		/// Gets the number of rows changed, inserted, or deleted by execution of the RETURNED_ITEM_DETAILS_Delete stored procedure.
		/// </summary>
		public int RecordsAffected
		{
			get {return _recordsAffected;}
		}
		
		/// <summary>
		/// 
		/// </summary>
		public SqlInt32 OrderDetailId
		{
			get {return _orderDetailId;}
			set
			{
				_orderDetailId = value;
				_orderDetailIdSet = true;
			}
		}
		#endregion
		
		#region Execute Methods
		/// <summary>
		/// This method calls the RETURNED_ITEM_DETAILS_Delete stored procedure.
		/// </summary>
		public virtual void Execute()
		{
			SqlCommand cmd = new SqlCommand();
			
			System.Diagnostics.Debug.Assert(this.ConnectionString.Length != 0, "You must first set the ConnectionString property before calling this method.");
			SqlConnection cn = new SqlConnection(this.ConnectionString);
			
			try
			{
				cmd.Connection = cn;
				cmd.CommandText = "[dbo].[RETURNED_ITEM_DETAILS_Delete]";
				cmd.CommandType = CommandType.StoredProcedure;
				
				#region Populate Parameters
				SqlParameter prmReturnValue = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int);
				prmReturnValue.Direction = ParameterDirection.ReturnValue;
				
				SqlParameter prmOrderDetailId = cmd.Parameters.Add("@OrderDetailId", SqlDbType.Int);
				prmOrderDetailId.Direction = ParameterDirection.Input;
				if (_orderDetailIdSet == true || this.OrderDetailId.IsNull == false)
				{
					prmOrderDetailId.Value = this.OrderDetailId;
				}
				#endregion
				
				#region Execute Command
				cn.Open();
				_recordsAffected = cmd.ExecuteNonQuery();
				#endregion
				
				#region Get Output Parameters
				if (prmReturnValue.Value != null && prmReturnValue.Value != DBNull.Value)
				{
					_returnValue = (int)prmReturnValue.Value;
				}
				
				#endregion
			}
			finally
			{
				if (cn.State == ConnectionState.Open)
				{
					cn.Close();
				}
				
				cn.Dispose();
				cmd.Dispose();
			}
		}
		
		/// <summary>
		/// This method calls the RETURNED_ITEM_DETAILS_Delete stored procedure.
		/// </summary>
		/// <param name="connectionString">The connection string to use</param>
		/// <param name="orderDetailId"></param>
		public static void Execute(
				#region Parameters
				string connectionString,
				SqlInt32 orderDetailId
				#endregion
		    )
		{
			RETURNED_ITEM_DETAILS_Delete rETURNED_ITEM_DETAILS_Delete = new RETURNED_ITEM_DETAILS_Delete();
			
			#region Assign Property Values
			rETURNED_ITEM_DETAILS_Delete.ConnectionString = connectionString;
			rETURNED_ITEM_DETAILS_Delete.OrderDetailId = orderDetailId;
			#endregion
			
			rETURNED_ITEM_DETAILS_Delete.Execute();
			
			#region Get Property Values
			
			#endregion
		}
		#endregion
	}
	#endregion
}
