//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//
//     Date:    1/13/2010
//     Time:    10:19 PM
//     Version: 5.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace HongPhat.DataAccess
{
	#region RETURNED_ITEM_DETAILS_Update Wrapper
    /// <summary>
    /// This class is a wrapper for the RETURNED_ITEM_DETAILS_Update stored procedure.
    /// </summary>
    public class RETURNED_ITEM_DETAILS_Update
    {
		#region Member Variables
		protected string _connectionString = String.Empty;
		protected int _recordsAffected = -1;
		protected int _returnValue = 0;
		protected SqlInt32 _orderDetailId = SqlInt32.Null;
		protected bool _orderDetailIdSet = false;
		protected SqlInt32 _originalOrderDetailId = SqlInt32.Null;
		protected bool _originalOrderDetailIdSet = false;
		protected SqlDecimal _quantity = SqlDecimal.Null;
		protected bool _quantitySet = false;
		protected SqlDateTime _returnDate = SqlDateTime.Null;
		protected bool _returnDateSet = false;
		protected SqlString _note = SqlString.Null;
		protected bool _noteSet = false;
		#endregion
		
		#region Constructors
		public RETURNED_ITEM_DETAILS_Update()
		{
		}
		
		public RETURNED_ITEM_DETAILS_Update(string connectionString)
		{
			this.ConnectionString = connectionString;
		}
		#endregion
		
		#region Public Properties
		/// <summary>
		/// The connection string to use when executing the RETURNED_ITEM_DETAILS_Update stored procedure.
		/// </summary>
		public string ConnectionString
		{
			get {return _connectionString;}
			set {_connectionString = value;}
		}
		
		/// <summary>
		/// Gets the return value from the RETURNED_ITEM_DETAILS_Update stored procedure.
		/// </summary>
		public int ReturnValue
		{
			get {return _returnValue;}
		}
		
		/// <summary>
		/// Gets the number of rows changed, inserted, or deleted by execution of the RETURNED_ITEM_DETAILS_Update stored procedure.
		/// </summary>
		public int RecordsAffected
		{
			get {return _recordsAffected;}
		}
		
		/// <summary>
		/// 
		/// </summary>
		public SqlInt32 OrderDetailId
		{
			get {return _orderDetailId;}
			set
			{
				_orderDetailId = value;
				_orderDetailIdSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlInt32 OriginalOrderDetailId
		{
			get {return _originalOrderDetailId;}
			set
			{
				_originalOrderDetailId = value;
				_originalOrderDetailIdSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlDecimal Quantity
		{
			get {return _quantity;}
			set
			{
				_quantity = value;
				_quantitySet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlDateTime ReturnDate
		{
			get {return _returnDate;}
			set
			{
				_returnDate = value;
				_returnDateSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlString Note
		{
			get {return _note;}
			set
			{
				_note = value;
				_noteSet = true;
			}
		}
		#endregion
		
		#region Execute Methods
		/// <summary>
		/// This method calls the RETURNED_ITEM_DETAILS_Update stored procedure.
		/// </summary>
		public virtual void Execute()
		{
			SqlCommand cmd = new SqlCommand();
			
			System.Diagnostics.Debug.Assert(this.ConnectionString.Length != 0, "You must first set the ConnectionString property before calling this method.");
			SqlConnection cn = new SqlConnection(this.ConnectionString);
			
			try
			{
				cmd.Connection = cn;
				cmd.CommandText = "[dbo].[RETURNED_ITEM_DETAILS_Update]";
				cmd.CommandType = CommandType.StoredProcedure;
				
				#region Populate Parameters
				SqlParameter prmReturnValue = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int);
				prmReturnValue.Direction = ParameterDirection.ReturnValue;
				
				SqlParameter prmOrderDetailId = cmd.Parameters.Add("@OrderDetailId", SqlDbType.Int);
				prmOrderDetailId.Direction = ParameterDirection.Input;
				if (_orderDetailIdSet == true || this.OrderDetailId.IsNull == false)
				{
					prmOrderDetailId.Value = this.OrderDetailId;
				}
				
				SqlParameter prmOriginalOrderDetailId = cmd.Parameters.Add("@OriginalOrderDetailId", SqlDbType.Int);
				prmOriginalOrderDetailId.Direction = ParameterDirection.Input;
				if (_originalOrderDetailIdSet == true || this.OriginalOrderDetailId.IsNull == false)
				{
					prmOriginalOrderDetailId.Value = this.OriginalOrderDetailId;
				}
				
				SqlParameter prmQuantity = cmd.Parameters.Add("@Quantity", SqlDbType.Decimal);
				prmQuantity.Direction = ParameterDirection.Input;
					prmQuantity.Precision = 18;
					prmQuantity.Scale = 0;
				if (_quantitySet == true || this.Quantity.IsNull == false)
				{
					prmQuantity.Value = this.Quantity;
				}
				
				SqlParameter prmReturnDate = cmd.Parameters.Add("@ReturnDate", SqlDbType.DateTime);
				prmReturnDate.Direction = ParameterDirection.Input;
				if (_returnDateSet == true || this.ReturnDate.IsNull == false)
				{
					prmReturnDate.Value = this.ReturnDate;
				}
				
				SqlParameter prmNote = cmd.Parameters.Add("@Note", SqlDbType.Text);
				prmNote.Direction = ParameterDirection.Input;
					prmNote.Size = 16;
				if (_noteSet == true || this.Note.IsNull == false)
				{
					prmNote.Value = this.Note;
				}
				#endregion
				
				#region Execute Command
				cn.Open();
				_recordsAffected = cmd.ExecuteNonQuery();
				#endregion
				
				#region Get Output Parameters
				if (prmReturnValue.Value != null && prmReturnValue.Value != DBNull.Value)
				{
					_returnValue = (int)prmReturnValue.Value;
				}
				
				#endregion
			}
			finally
			{
				if (cn.State == ConnectionState.Open)
				{
					cn.Close();
				}
				
				cn.Dispose();
				cmd.Dispose();
			}
		}
		
		/// <summary>
		/// This method calls the RETURNED_ITEM_DETAILS_Update stored procedure.
		/// </summary>
		/// <param name="connectionString">The connection string to use</param>
		/// <param name="orderDetailId"></param>
		/// <param name="originalOrderDetailId"></param>
		/// <param name="quantity"></param>
		/// <param name="returnDate"></param>
		/// <param name="note"></param>
		public static void Execute(
				#region Parameters
				string connectionString,
				SqlInt32 orderDetailId,
				SqlInt32 originalOrderDetailId,
				SqlDecimal quantity,
				SqlDateTime returnDate,
				SqlString note
				#endregion
		    )
		{
			RETURNED_ITEM_DETAILS_Update rETURNED_ITEM_DETAILS_Update = new RETURNED_ITEM_DETAILS_Update();
			
			#region Assign Property Values
			rETURNED_ITEM_DETAILS_Update.ConnectionString = connectionString;
			rETURNED_ITEM_DETAILS_Update.OrderDetailId = orderDetailId;
			rETURNED_ITEM_DETAILS_Update.OriginalOrderDetailId = originalOrderDetailId;
			rETURNED_ITEM_DETAILS_Update.Quantity = quantity;
			rETURNED_ITEM_DETAILS_Update.ReturnDate = returnDate;
			rETURNED_ITEM_DETAILS_Update.Note = note;
			#endregion
			
			rETURNED_ITEM_DETAILS_Update.Execute();
			
			#region Get Property Values
			
			#endregion
		}
		#endregion
	}
	#endregion
}
