//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//
//     Date:    1/13/2010
//     Time:    10:18 PM
//     Version: 5.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace HongPhat.DataAccess
{
	#region ITEMS_Insert Wrapper
    /// <summary>
    /// This class is a wrapper for the ITEMS_Insert stored procedure.
    /// </summary>
    public class ITEMS_Insert
    {
		#region Member Variables
		protected string _connectionString = String.Empty;
		protected int _recordsAffected = -1;
		protected int _returnValue = 0;
		protected SqlInt32 _itemId = SqlInt32.Null;
		protected bool _itemIdSet = false;
		protected SqlString _itemName = SqlString.Null;
		protected bool _itemNameSet = false;
		protected SqlString _createdBy = SqlString.Null;
		protected bool _createdBySet = false;
		protected SqlDateTime _createdDate = SqlDateTime.Null;
		protected bool _createdDateSet = false;
		protected SqlString _modifiedBy = SqlString.Null;
		protected bool _modifiedBySet = false;
		protected SqlDateTime _modifiedDate = SqlDateTime.Null;
		protected bool _modifiedDateSet = false;
		protected SqlInt32 _deleted = SqlInt32.Null;
		protected bool _deletedSet = false;
		protected SqlDecimal _totalQuantity = SqlDecimal.Null;
		protected bool _totalQuantitySet = false;
		protected SqlString _measurement = SqlString.Null;
		protected bool _measurementSet = false;
		#endregion
		
		#region Constructors
		public ITEMS_Insert()
		{
		}
		
		public ITEMS_Insert(string connectionString)
		{
			this.ConnectionString = connectionString;
		}
		#endregion
		
		#region Public Properties
		/// <summary>
		/// The connection string to use when executing the ITEMS_Insert stored procedure.
		/// </summary>
		public string ConnectionString
		{
			get {return _connectionString;}
			set {_connectionString = value;}
		}
		
		/// <summary>
		/// Gets the return value from the ITEMS_Insert stored procedure.
		/// </summary>
		public int ReturnValue
		{
			get {return _returnValue;}
		}
		
		/// <summary>
		/// Gets the number of rows changed, inserted, or deleted by execution of the ITEMS_Insert stored procedure.
		/// </summary>
		public int RecordsAffected
		{
			get {return _recordsAffected;}
		}
		
		/// <summary>
		/// 
		/// </summary>
		public SqlInt32 ItemId
		{
			get {return _itemId;}
			set
			{
				_itemId = value;
				_itemIdSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlString ItemName
		{
			get {return _itemName;}
			set
			{
				_itemName = value;
				_itemNameSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlString CreatedBy
		{
			get {return _createdBy;}
			set
			{
				_createdBy = value;
				_createdBySet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlDateTime CreatedDate
		{
			get {return _createdDate;}
			set
			{
				_createdDate = value;
				_createdDateSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlString ModifiedBy
		{
			get {return _modifiedBy;}
			set
			{
				_modifiedBy = value;
				_modifiedBySet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlDateTime ModifiedDate
		{
			get {return _modifiedDate;}
			set
			{
				_modifiedDate = value;
				_modifiedDateSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlInt32 Deleted
		{
			get {return _deleted;}
			set
			{
				_deleted = value;
				_deletedSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlDecimal TotalQuantity
		{
			get {return _totalQuantity;}
			set
			{
				_totalQuantity = value;
				_totalQuantitySet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlString Measurement
		{
			get {return _measurement;}
			set
			{
				_measurement = value;
				_measurementSet = true;
			}
		}
		#endregion
		
		#region Execute Methods
		/// <summary>
		/// This method calls the ITEMS_Insert stored procedure.
		/// </summary>
		public virtual void Execute()
		{
			SqlCommand cmd = new SqlCommand();
			
			System.Diagnostics.Debug.Assert(this.ConnectionString.Length != 0, "You must first set the ConnectionString property before calling this method.");
			SqlConnection cn = new SqlConnection(this.ConnectionString);
			
			try
			{
				cmd.Connection = cn;
				cmd.CommandText = "[dbo].[ITEMS_Insert]";
				cmd.CommandType = CommandType.StoredProcedure;
				
				#region Populate Parameters
				SqlParameter prmReturnValue = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int);
				prmReturnValue.Direction = ParameterDirection.ReturnValue;
				
				SqlParameter prmItemId = cmd.Parameters.Add("@ItemId", SqlDbType.Int);
				if (_itemIdSet == true)
				{
				prmItemId.Direction = ParameterDirection.InputOutput;
				}
				else
				{
					prmItemId.Direction = ParameterDirection.Output;
				}
				if (_itemIdSet == true || this.ItemId.IsNull == false)
				{
					prmItemId.Value = this.ItemId;
				}
				
				SqlParameter prmItemName = cmd.Parameters.Add("@ItemName", SqlDbType.NVarChar);
				prmItemName.Direction = ParameterDirection.Input;
					prmItemName.Size = 250;
				if (_itemNameSet == true || this.ItemName.IsNull == false)
				{
					prmItemName.Value = this.ItemName;
				}
				
				SqlParameter prmCreatedBy = cmd.Parameters.Add("@CreatedBy", SqlDbType.NVarChar);
				prmCreatedBy.Direction = ParameterDirection.Input;
					prmCreatedBy.Size = 250;
				if (_createdBySet == true || this.CreatedBy.IsNull == false)
				{
					prmCreatedBy.Value = this.CreatedBy;
				}
				
				SqlParameter prmCreatedDate = cmd.Parameters.Add("@CreatedDate", SqlDbType.DateTime);
				prmCreatedDate.Direction = ParameterDirection.Input;
				if (_createdDateSet == true || this.CreatedDate.IsNull == false)
				{
					prmCreatedDate.Value = this.CreatedDate;
				}
				
				SqlParameter prmModifiedBy = cmd.Parameters.Add("@ModifiedBy", SqlDbType.NVarChar);
				prmModifiedBy.Direction = ParameterDirection.Input;
					prmModifiedBy.Size = 250;
				if (_modifiedBySet == true || this.ModifiedBy.IsNull == false)
				{
					prmModifiedBy.Value = this.ModifiedBy;
				}
				
				SqlParameter prmModifiedDate = cmd.Parameters.Add("@ModifiedDate", SqlDbType.DateTime);
				prmModifiedDate.Direction = ParameterDirection.Input;
				if (_modifiedDateSet == true || this.ModifiedDate.IsNull == false)
				{
					prmModifiedDate.Value = this.ModifiedDate;
				}
				
				SqlParameter prmDeleted = cmd.Parameters.Add("@Deleted", SqlDbType.Int);
				prmDeleted.Direction = ParameterDirection.Input;
				if (_deletedSet == true || this.Deleted.IsNull == false)
				{
					prmDeleted.Value = this.Deleted;
				}
				
				SqlParameter prmTotalQuantity = cmd.Parameters.Add("@TotalQuantity", SqlDbType.Decimal);
				prmTotalQuantity.Direction = ParameterDirection.Input;
					prmTotalQuantity.Precision = 18;
					prmTotalQuantity.Scale = 0;
				if (_totalQuantitySet == true || this.TotalQuantity.IsNull == false)
				{
					prmTotalQuantity.Value = this.TotalQuantity;
				}
				
				SqlParameter prmMeasurement = cmd.Parameters.Add("@Measurement", SqlDbType.NVarChar);
				prmMeasurement.Direction = ParameterDirection.Input;
					prmMeasurement.Size = 150;
				if (_measurementSet == true || this.Measurement.IsNull == false)
				{
					prmMeasurement.Value = this.Measurement;
				}
				#endregion
				
				#region Execute Command
				cn.Open();
				_recordsAffected = cmd.ExecuteNonQuery();
				#endregion
				
				#region Get Output Parameters
				if (prmReturnValue.Value != null && prmReturnValue.Value != DBNull.Value)
				{
					_returnValue = (int)prmReturnValue.Value;
				}
				
				if (prmItemId != null && prmItemId.Value != null)
				{
					if (prmItemId.Value is SqlInt32)
					{
						this.ItemId = (SqlInt32)prmItemId.Value;
					}
					else
					{
						if (prmItemId.Value != DBNull.Value)
						{
							this.ItemId = new SqlInt32((int)prmItemId.Value);
						}
						else
						{
							this.ItemId = SqlInt32.Null;
						}
					}
				}
				else
				{
					this.ItemId = SqlInt32.Null;
				}
				#endregion
			}
			finally
			{
				if (cn.State == ConnectionState.Open)
				{
					cn.Close();
				}
				
				cn.Dispose();
				cmd.Dispose();
			}
		}
		
		/// <summary>
		/// This method calls the ITEMS_Insert stored procedure.
		/// </summary>
		/// <param name="connectionString">The connection string to use</param>
		/// <param name="itemName"></param>
		/// <param name="createdBy"></param>
		/// <param name="createdDate"></param>
		/// <param name="modifiedBy"></param>
		/// <param name="modifiedDate"></param>
		/// <param name="deleted"></param>
		/// <param name="totalQuantity"></param>
		/// <param name="measurement"></param>
		/// <param name="itemId"></param>
		public static void Execute(
				#region Parameters
				string connectionString,
				SqlString itemName,
				SqlString createdBy,
				SqlDateTime createdDate,
				SqlString modifiedBy,
				SqlDateTime modifiedDate,
				SqlInt32 deleted,
				SqlDecimal totalQuantity,
				SqlString measurement,
				ref SqlInt32 itemId
				#endregion
		    )
		{
			ITEMS_Insert iTEMS_Insert = new ITEMS_Insert();
			
			#region Assign Property Values
			iTEMS_Insert.ConnectionString = connectionString;
			iTEMS_Insert.ItemId = itemId;
			iTEMS_Insert.ItemName = itemName;
			iTEMS_Insert.CreatedBy = createdBy;
			iTEMS_Insert.CreatedDate = createdDate;
			iTEMS_Insert.ModifiedBy = modifiedBy;
			iTEMS_Insert.ModifiedDate = modifiedDate;
			iTEMS_Insert.Deleted = deleted;
			iTEMS_Insert.TotalQuantity = totalQuantity;
			iTEMS_Insert.Measurement = measurement;
			#endregion
			
			iTEMS_Insert.Execute();
			
			#region Get Property Values
			itemId = iTEMS_Insert.ItemId;
			#endregion
		}
		#endregion
	}
	#endregion
}
