//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//
//     Date:    1/13/2010
//     Time:    10:18 PM
//     Version: 5.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace HongPhat.DataAccess
{
	#region AGENT_KIND_Delete Wrapper
    /// <summary>
    /// This class is a wrapper for the AGENT_KIND_Delete stored procedure.
    /// </summary>
    public class AGENT_KIND_Delete
    {
		#region Member Variables
		protected string _connectionString = String.Empty;
		protected int _recordsAffected = -1;
		protected int _returnValue = 0;
		protected SqlInt32 _idAgentKind = SqlInt32.Null;
		protected bool _idAgentKindSet = false;
		#endregion
		
		#region Constructors
		public AGENT_KIND_Delete()
		{
		}
		
		public AGENT_KIND_Delete(string connectionString)
		{
			this.ConnectionString = connectionString;
		}
		#endregion
		
		#region Public Properties
		/// <summary>
		/// The connection string to use when executing the AGENT_KIND_Delete stored procedure.
		/// </summary>
		public string ConnectionString
		{
			get {return _connectionString;}
			set {_connectionString = value;}
		}
		
		/// <summary>
		/// Gets the return value from the AGENT_KIND_Delete stored procedure.
		/// </summary>
		public int ReturnValue
		{
			get {return _returnValue;}
		}
		
		/// <summary>
		/// Gets the number of rows changed, inserted, or deleted by execution of the AGENT_KIND_Delete stored procedure.
		/// </summary>
		public int RecordsAffected
		{
			get {return _recordsAffected;}
		}
		
		/// <summary>
		/// 
		/// </summary>
		public SqlInt32 IdAgentKind
		{
			get {return _idAgentKind;}
			set
			{
				_idAgentKind = value;
				_idAgentKindSet = true;
			}
		}
		#endregion
		
		#region Execute Methods
		/// <summary>
		/// This method calls the AGENT_KIND_Delete stored procedure.
		/// </summary>
		public virtual void Execute()
		{
			SqlCommand cmd = new SqlCommand();
			
			System.Diagnostics.Debug.Assert(this.ConnectionString.Length != 0, "You must first set the ConnectionString property before calling this method.");
			SqlConnection cn = new SqlConnection(this.ConnectionString);
			
			try
			{
				cmd.Connection = cn;
				cmd.CommandText = "[dbo].[AGENT_KIND_Delete]";
				cmd.CommandType = CommandType.StoredProcedure;
				
				#region Populate Parameters
				SqlParameter prmReturnValue = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int);
				prmReturnValue.Direction = ParameterDirection.ReturnValue;
				
				SqlParameter prmIdAgentKind = cmd.Parameters.Add("@IdAgentKind", SqlDbType.Int);
				prmIdAgentKind.Direction = ParameterDirection.Input;
				if (_idAgentKindSet == true || this.IdAgentKind.IsNull == false)
				{
					prmIdAgentKind.Value = this.IdAgentKind;
				}
				#endregion
				
				#region Execute Command
				cn.Open();
				_recordsAffected = cmd.ExecuteNonQuery();
				#endregion
				
				#region Get Output Parameters
				if (prmReturnValue.Value != null && prmReturnValue.Value != DBNull.Value)
				{
					_returnValue = (int)prmReturnValue.Value;
				}
				
				#endregion
			}
			finally
			{
				if (cn.State == ConnectionState.Open)
				{
					cn.Close();
				}
				
				cn.Dispose();
				cmd.Dispose();
			}
		}
		
		/// <summary>
		/// This method calls the AGENT_KIND_Delete stored procedure.
		/// </summary>
		/// <param name="connectionString">The connection string to use</param>
		/// <param name="idAgentKind"></param>
		public static void Execute(
				#region Parameters
				string connectionString,
				SqlInt32 idAgentKind
				#endregion
		    )
		{
			AGENT_KIND_Delete aGENT_KIND_Delete = new AGENT_KIND_Delete();
			
			#region Assign Property Values
			aGENT_KIND_Delete.ConnectionString = connectionString;
			aGENT_KIND_Delete.IdAgentKind = idAgentKind;
			#endregion
			
			aGENT_KIND_Delete.Execute();
			
			#region Get Property Values
			
			#endregion
		}
		#endregion
	}
	#endregion
}
