//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//
//     Date:    1/13/2010
//     Time:    10:19 PM
//     Version: 5.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace HongPhat.DataAccess
{
	#region SELL_PRICE_Update Wrapper
    /// <summary>
    /// This class is a wrapper for the SELL_PRICE_Update stored procedure.
    /// </summary>
    public class SELL_PRICE_Update
    {
		#region Member Variables
		protected string _connectionString = String.Empty;
		protected int _recordsAffected = -1;
		protected int _returnValue = 0;
		protected SqlInt32 _id = SqlInt32.Null;
		protected bool _idSet = false;
		protected SqlInt32 _itemId = SqlInt32.Null;
		protected bool _itemIdSet = false;
		protected SqlInt32 _agentId = SqlInt32.Null;
		protected bool _agentIdSet = false;
		protected SqlDecimal _sellPrice = SqlDecimal.Null;
		protected bool _sellPriceSet = false;
		protected SqlDateTime _createdDate = SqlDateTime.Null;
		protected bool _createdDateSet = false;
		protected SqlString _createdBy = SqlString.Null;
		protected bool _createdBySet = false;
		protected SqlString _modifiedBy = SqlString.Null;
		protected bool _modifiedBySet = false;
		protected SqlDateTime _modifiedDate = SqlDateTime.Null;
		protected bool _modifiedDateSet = false;
		protected SqlInt32 _deleted = SqlInt32.Null;
		protected bool _deletedSet = false;
		#endregion
		
		#region Constructors
		public SELL_PRICE_Update()
		{
		}
		
		public SELL_PRICE_Update(string connectionString)
		{
			this.ConnectionString = connectionString;
		}
		#endregion
		
		#region Public Properties
		/// <summary>
		/// The connection string to use when executing the SELL_PRICE_Update stored procedure.
		/// </summary>
		public string ConnectionString
		{
			get {return _connectionString;}
			set {_connectionString = value;}
		}
		
		/// <summary>
		/// Gets the return value from the SELL_PRICE_Update stored procedure.
		/// </summary>
		public int ReturnValue
		{
			get {return _returnValue;}
		}
		
		/// <summary>
		/// Gets the number of rows changed, inserted, or deleted by execution of the SELL_PRICE_Update stored procedure.
		/// </summary>
		public int RecordsAffected
		{
			get {return _recordsAffected;}
		}
		
		/// <summary>
		/// 
		/// </summary>
		public SqlInt32 Id
		{
			get {return _id;}
			set
			{
				_id = value;
				_idSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlInt32 ItemId
		{
			get {return _itemId;}
			set
			{
				_itemId = value;
				_itemIdSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlInt32 AgentId
		{
			get {return _agentId;}
			set
			{
				_agentId = value;
				_agentIdSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlDecimal SellPrice
		{
			get {return _sellPrice;}
			set
			{
				_sellPrice = value;
				_sellPriceSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlDateTime CreatedDate
		{
			get {return _createdDate;}
			set
			{
				_createdDate = value;
				_createdDateSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlString CreatedBy
		{
			get {return _createdBy;}
			set
			{
				_createdBy = value;
				_createdBySet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlString ModifiedBy
		{
			get {return _modifiedBy;}
			set
			{
				_modifiedBy = value;
				_modifiedBySet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlDateTime ModifiedDate
		{
			get {return _modifiedDate;}
			set
			{
				_modifiedDate = value;
				_modifiedDateSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlInt32 Deleted
		{
			get {return _deleted;}
			set
			{
				_deleted = value;
				_deletedSet = true;
			}
		}
		#endregion
		
		#region Execute Methods
		/// <summary>
		/// This method calls the SELL_PRICE_Update stored procedure.
		/// </summary>
		public virtual void Execute()
		{
			SqlCommand cmd = new SqlCommand();
			
			System.Diagnostics.Debug.Assert(this.ConnectionString.Length != 0, "You must first set the ConnectionString property before calling this method.");
			SqlConnection cn = new SqlConnection(this.ConnectionString);
			
			try
			{
				cmd.Connection = cn;
				cmd.CommandText = "[dbo].[SELL_PRICE_Update]";
				cmd.CommandType = CommandType.StoredProcedure;
				
				#region Populate Parameters
				SqlParameter prmReturnValue = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int);
				prmReturnValue.Direction = ParameterDirection.ReturnValue;
				
				SqlParameter prmId = cmd.Parameters.Add("@Id", SqlDbType.Int);
				prmId.Direction = ParameterDirection.Input;
				if (_idSet == true || this.Id.IsNull == false)
				{
					prmId.Value = this.Id;
				}
				
				SqlParameter prmItemId = cmd.Parameters.Add("@ItemId", SqlDbType.Int);
				prmItemId.Direction = ParameterDirection.Input;
				if (_itemIdSet == true || this.ItemId.IsNull == false)
				{
					prmItemId.Value = this.ItemId;
				}
				
				SqlParameter prmAgentId = cmd.Parameters.Add("@AgentId", SqlDbType.Int);
				prmAgentId.Direction = ParameterDirection.Input;
				if (_agentIdSet == true || this.AgentId.IsNull == false)
				{
					prmAgentId.Value = this.AgentId;
				}
				
				SqlParameter prmSellPrice = cmd.Parameters.Add("@SellPrice", SqlDbType.Decimal);
				prmSellPrice.Direction = ParameterDirection.Input;
					prmSellPrice.Precision = 18;
					prmSellPrice.Scale = 0;
				if (_sellPriceSet == true || this.SellPrice.IsNull == false)
				{
					prmSellPrice.Value = this.SellPrice;
				}
				
				SqlParameter prmCreatedDate = cmd.Parameters.Add("@CreatedDate", SqlDbType.DateTime);
				prmCreatedDate.Direction = ParameterDirection.Input;
				if (_createdDateSet == true || this.CreatedDate.IsNull == false)
				{
					prmCreatedDate.Value = this.CreatedDate;
				}
				
				SqlParameter prmCreatedBy = cmd.Parameters.Add("@CreatedBy", SqlDbType.NVarChar);
				prmCreatedBy.Direction = ParameterDirection.Input;
					prmCreatedBy.Size = 250;
				if (_createdBySet == true || this.CreatedBy.IsNull == false)
				{
					prmCreatedBy.Value = this.CreatedBy;
				}
				
				SqlParameter prmModifiedBy = cmd.Parameters.Add("@ModifiedBy", SqlDbType.NVarChar);
				prmModifiedBy.Direction = ParameterDirection.Input;
					prmModifiedBy.Size = 250;
				if (_modifiedBySet == true || this.ModifiedBy.IsNull == false)
				{
					prmModifiedBy.Value = this.ModifiedBy;
				}
				
				SqlParameter prmModifiedDate = cmd.Parameters.Add("@ModifiedDate", SqlDbType.DateTime);
				prmModifiedDate.Direction = ParameterDirection.Input;
				if (_modifiedDateSet == true || this.ModifiedDate.IsNull == false)
				{
					prmModifiedDate.Value = this.ModifiedDate;
				}
				
				SqlParameter prmDeleted = cmd.Parameters.Add("@Deleted", SqlDbType.Int);
				prmDeleted.Direction = ParameterDirection.Input;
				if (_deletedSet == true || this.Deleted.IsNull == false)
				{
					prmDeleted.Value = this.Deleted;
				}
				#endregion
				
				#region Execute Command
				cn.Open();
				_recordsAffected = cmd.ExecuteNonQuery();
				#endregion
				
				#region Get Output Parameters
				if (prmReturnValue.Value != null && prmReturnValue.Value != DBNull.Value)
				{
					_returnValue = (int)prmReturnValue.Value;
				}
				
				#endregion
			}
			finally
			{
				if (cn.State == ConnectionState.Open)
				{
					cn.Close();
				}
				
				cn.Dispose();
				cmd.Dispose();
			}
		}
		
		/// <summary>
		/// This method calls the SELL_PRICE_Update stored procedure.
		/// </summary>
		/// <param name="connectionString">The connection string to use</param>
		/// <param name="id"></param>
		/// <param name="itemId"></param>
		/// <param name="agentId"></param>
		/// <param name="sellPrice"></param>
		/// <param name="createdDate"></param>
		/// <param name="createdBy"></param>
		/// <param name="modifiedBy"></param>
		/// <param name="modifiedDate"></param>
		/// <param name="deleted"></param>
		public static void Execute(
				#region Parameters
				string connectionString,
				SqlInt32 id,
				SqlInt32 itemId,
				SqlInt32 agentId,
				SqlDecimal sellPrice,
				SqlDateTime createdDate,
				SqlString createdBy,
				SqlString modifiedBy,
				SqlDateTime modifiedDate,
				SqlInt32 deleted
				#endregion
		    )
		{
			SELL_PRICE_Update sELL_PRICE_Update = new SELL_PRICE_Update();
			
			#region Assign Property Values
			sELL_PRICE_Update.ConnectionString = connectionString;
			sELL_PRICE_Update.Id = id;
			sELL_PRICE_Update.ItemId = itemId;
			sELL_PRICE_Update.AgentId = agentId;
			sELL_PRICE_Update.SellPrice = sellPrice;
			sELL_PRICE_Update.CreatedDate = createdDate;
			sELL_PRICE_Update.CreatedBy = createdBy;
			sELL_PRICE_Update.ModifiedBy = modifiedBy;
			sELL_PRICE_Update.ModifiedDate = modifiedDate;
			sELL_PRICE_Update.Deleted = deleted;
			#endregion
			
			sELL_PRICE_Update.Execute();
			
			#region Get Property Values
			
			#endregion
		}
		#endregion
	}
	#endregion
}
